export const chats = [
  {
    users: ['user1', 'usern'],
    messages: [{
      from: "user1",
      to: "usern",
      text: "Hey Alice, how are you?",
      date: "2025-07-10",
      time: "14:32",
      isEdited: false,
    },
    {
      from: "usern",
      to: "user1",
      text: "I’m good! You?",
      date: "2025-07-10",
      time: "14:32",
      isEdited: false,
    },
    {
      from: "user1",
      to: "usern",
      text: "Same Here Dude, What are you doing currently? ",
      date: "2025-07-10",
      time: "14:33",
      isEdited: false,
    },
    {
      from: "usern",
      to: "user1",
      text: "I've Started a business with business womens...",
      date: "2025-07-10",
      time: "14:33",
      isEdited: false,
    },
    {
      from: "user1",
      to: "usern",
      text: "Oh, You mean you have started a Randikhana... ?",
      date: "2025-07-10",
      time: "14:33",
      isEdited: false,
    },
    {
      from: "usern",
      to: "user1",
      text: "Yess....",
      date: "2025-07-10",
      time: "14:34",
      isEdited: false,
    },
  ]},
  {
    users: ['user1', 'user3'],
    messages: [{
      from: "user1",
      to: "user3",
      text: "Hello Dude whatsapp",
      date: "2025-07-10",
      time: "14:32",
      isEdited: false,
    },
    {
      from: "user3",
      to: "user1",
      text: "I’m good buddy! You?",
      date: "2025-07-10",
      time: "14:32",
      isEdited: false,
    },
    {
      from: "user1",
      to: "user3",
      text: "Same Here man... ",
      date: "2025-07-10",
      time: "14:33",
      isEdited: false,
    },
    {
      from: "user1",
      to: "user3",
      text: "Same Here man... with new message",
      date: "2025-07-10",
      time: "14:33",
      isEdited: false,
    },
    {
      from: "user3",
      to: "user1",
      text: "Some message part 1 here",
      date: "2025-07-10",
      time: "14:33",
      isEdited: false,
    },
    {
      from: "user1",
      to: "user3",
      text: "Some message 2 here",
      date: "2025-07-10",
      time: "14:33",
      isEdited: false,
    },
    {
      from: "user3",
      to: "user1",
      text: "alsdfjlaskdjflkjasdf",
      date: "2025-07-10",
      time: "14:34",
      isEdited: false,
    },
  ]},
];
